[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Explicitly allow indexing
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/sitemap_index.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/feed"
  to = "/sitemap.xml"
  status = 301
