name = "seo-test"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-04-25"

[site]
bucket = "./.next"
entry-point = ".next/server/pages"

[build]
command = "npm run build"
destination = ".next"
watch_dir = "src"

[env.production]
workers_dev = false
route = "portolio.sophat.workers.dev/*"

[env.staging]
workers_dev = true