import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import { currentDomain } from '../lib/constants';

interface SitemapRoute {
    path: string;
    changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
    priority: number;
    lastmod?: string;
}

interface PostData {
    id: string;
    slug: string;
    published: boolean;
    createdAt: string;
    updatedAt?: string;
}

interface ProjectData {
    id: string;
    title: string;
    published: boolean;
    createdAt: string;
}

// Define static routes for the site (excluding admin/auth pages)
const STATIC_ROUTES: SitemapRoute[] = [
    { path: '/', changefreq: 'weekly', priority: 1.0 },
    { path: '/about', changefreq: 'monthly', priority: 0.8 },
    { path: '/contact', changefreq: 'monthly', priority: 0.8 },
    { path: '/gallery', changefreq: 'monthly', priority: 0.8 },
    { path: '/posts', changefreq: 'weekly', priority: 0.9 },
    { path: '/projects', changefreq: 'monthly', priority: 0.8 },
    // Add important static files that should be indexable
    { path: '/sitemap.xml', changefreq: 'weekly', priority: 0.3 },
    { path: '/robots.txt', changefreq: 'monthly', priority: 0.1 },
];

// Define paths that should be excluded from sitemap
const EXCLUDED_PATHS = [
    '/admin/',
    '/login',
    '/(auth)/',
    '/posts/[slug]', // This is a template, not an actual page
    '/data/', // JSON data files
    '/google', // Google verification files
];

// Get dynamic post detail routes from post data
function fetchPostRoutes(): SitemapRoute[] {
    try {
        // Read posts from JSON file
        const postsFilePath = join(process.cwd(), 'public/data/post.json');

        const postsData = JSON.parse(readFileSync(postsFilePath, 'utf-8'));
        const posts = postsData.posts as PostData[];

        // Filter published posts and create route objects
        const publishedPosts = posts.filter(post => post.published);
        console.log(`${publishedPosts.length} posts are published and will be included in sitemap`);

        return publishedPosts.map(post => ({
            path: `/posts/${post.slug}`,
            changefreq: 'monthly' as const,
            priority: 0.7,
            lastmod: new Date(post.updatedAt || post.createdAt).toISOString().split('T')[0]
        }));
    } catch (error) {
        console.error('Error reading post data:', error);
        return [];
    }
}

// Get dynamic project routes from project data
function fetchProjectRoutes(): SitemapRoute[] {
    try {
        // Read projects from JSON file
        const projectsFilePath = join(process.cwd(), 'public/data/project.json');

        const projectsData = JSON.parse(readFileSync(projectsFilePath, 'utf-8'));
        const projects = projectsData.posts as ProjectData[]; // Note: projects are stored in 'posts' array

        // Filter published projects and create route objects
        const publishedProjects = projects.filter(project => project.published);
        console.log(`${publishedProjects.length} projects are published and will be included in sitemap`);        return publishedProjects.map(project => ({
            path: `/projects/${project.id}`,
            changefreq: 'monthly' as const,
            priority: 0.6,
            lastmod: new Date(project.createdAt).toISOString().split('T')[0]
        }));
    } catch (error) {
        console.error('Error reading project data:', error);
        return [];
    }
}

// Generate and save the sitemap
export function createSitemap(): void {
    try {
        const today = new Date().toISOString().split('T')[0];
        const postRoutes = fetchPostRoutes();
        const allRoutes = [...STATIC_ROUTES, ...postRoutes];

        // Filter out any routes that should be excluded
        const filteredRoutes = allRoutes.filter(route => 
            !EXCLUDED_PATHS.some(excluded => route.path.includes(excluded.replace('/', '')))
        );

        console.log('\n📁 Site Routes:');
        console.log(`📊 Total routes: ${filteredRoutes.length}`);
        console.log(`📝 Static routes: ${STATIC_ROUTES.length}`);
        console.log(`📄 Post routes: ${postRoutes.length}`);
        console.log(`🚫 Excluded patterns: ${EXCLUDED_PATHS.join(', ')}`);

        filteredRoutes.forEach((route, index) => {
            const isLast = index === filteredRoutes.length - 1;
            console.log(`${isLast ? ' └──' : ' ├──'} ${route.path}`);
        });

        console.log('\n');

        const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
            <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
                <!-- Generated by PPhat's sitemap generator -->
                ${filteredRoutes.map(route => `
                    <url>
                        <loc>${`${currentDomain.trim()}${route.path}`}</loc>
                        <lastmod>${route.lastmod || today}</lastmod>
                        <changefreq>${route.changefreq}</changefreq>
                        <priority>${route.priority.toFixed(1)}</priority>
                    </url>
                `).join('')}
            </urlset>`;

        const outputPath = join(process.cwd(), 'public/sitemap.xml');
        writeFileSync(outputPath, sitemap, 'utf-8');
        console.log(`✅ Sitemap generated successfully at ${outputPath}`);
        console.log(`🔗 Sitemap URL: ${currentDomain}/sitemap.xml`);
        console.log(`📋 Total indexable pages: ${filteredRoutes.length}`);
    } catch (error) {
        console.error('❌ Error generating sitemap:', error);
        process.exit(1);
    }
}

// Run the generator
createSitemap();
